"""
AgentControllerV6: Week 6 bounded agent loop with persistent memory.

What is NEW compared to Week 5:
  1. Memory loaded from MemoryStore before the loop (bound to session customer_id).
  2. memory_context placed in AgentState — read-only for the planner.
  3. Memory written after TICKET_CREATED — the controller writes it, not the model.
  4. retry_count tracked per the Week 6 State Model spec (max 1 per failed call).
  5. State transitions printed clearly so you can follow the state machine.

Security boundaries (unchanged from Week 5):
  - customer_id always comes from the trusted session dict, never model output.
  - human_approval_token is generated by the controller, never by the model.
  - Memory context is informational only — it cannot authorize escalation.
  - Tool arguments that include identity fields are rejected before execution.
"""
from __future__ import annotations

import os
import sys
import uuid
from pathlib import Path
from typing import Callable, Optional

# ── Path setup: import tools from centenary-RAG ──────────────────────────────
_RAG = Path(__file__).resolve().parent.parent / "centenary-RAG"
sys.path.insert(0, str(_RAG))

from orchestrator import CallerContext, ToolOrchestrator   # noqa: E402
from tools import (                                         # noqa: E402
    default_service_data,
    make_get_service_status_tool,
    make_get_ticket_status_tool,
    make_create_support_ticket_tool,
    make_escalate_support_case_tool,
    make_search_knowledge_base_tool,
)

# ── Local Week 6 imports ──────────────────────────────────────────────────────
from agent_state_v6 import AgentState
from memory_store import MemoryStore
from planner_v6 import ALLOWED_ACTIONS, ALLOWED_TOOLS

MAX_ITERATIONS = 4
MAX_RETRY      = 1

_NO_TOOL_ACTIONS = {"answer_from_evidence", "ask_for_clarification", "refuse_or_handoff"}


# ── Minimal null pipeline (returns no KB results) ─────────────────────────────
class _NullSource:
    marker = ""; doc_id = ""; doc_title = ""; score = 0.0; text = ""

class _NullAnswer:
    sources: list = []

class NullPipeline:
    """Stand-in pipeline for demos that do not exercise knowledge-base search."""
    def answer(self, query: str, k: int = 4) -> _NullAnswer:
        return _NullAnswer()


# ── Controller ────────────────────────────────────────────────────────────────

class AgentControllerV6:
    """
    Runs one customer request through the bounded Sense→Plan→Act→Observe loop
    with persistent memory integration.

    Parameters
    ----------
    memory_store     : MemoryStore — shared across sessions to persist case history
    planner          : any object with decide(state, iterations_left) → dict | None
    pipeline         : RAG pipeline (or NullPipeline if search is not needed)
    ticket_store     : shared in-memory ticket dict
    approvals        : shared approval-token dict
    approval_handler : (case_ref, reason, urgency) → bool
                       True = approved, False = denied.  Defaults to console prompt.
    simulate_*       : {"value": bool} fault-injection handles
    """

    def __init__(
        self,
        memory_store: MemoryStore,
        planner,
        pipeline=None,
        ticket_store: Optional[dict] = None,
        approvals: Optional[dict] = None,
        simulate_service_down: Optional[dict] = None,
        simulate_ticket_down: Optional[dict] = None,
        simulate_escalation_down: Optional[dict] = None,
        simulate_malformed: Optional[dict] = None,
        approval_handler: Optional[Callable] = None,
    ):
        self._memory    = memory_store
        self._planner   = planner
        self._approvals = approvals if approvals is not None else {}

        simulate_service_down    = simulate_service_down    or {"value": False}
        simulate_ticket_down     = simulate_ticket_down     or {"value": False}
        simulate_escalation_down = simulate_escalation_down or {"value": False}
        simulate_malformed       = simulate_malformed       or {"value": False}

        self._approval_handler = approval_handler or _console_approval_gate

        _pipeline  = pipeline or NullPipeline()
        _tickets   = ticket_store if ticket_store is not None else {}
        _svc_data  = default_service_data()

        tools = [
            make_search_knowledge_base_tool(_pipeline, {"value": False}),
            make_get_service_status_tool(_svc_data, simulate_service_down),
            make_get_ticket_status_tool(_tickets, simulate_ticket_down),
            make_create_support_ticket_tool(
                _tickets, simulate_ticket_down, simulate_malformed),
            make_escalate_support_case_tool(
                self._approvals, simulate_escalation_down),
        ]
        self._orchestrator = ToolOrchestrator(tools)

    # ── Public entry point ────────────────────────────────────────────────────

    def run(self, user_request: str, session: dict) -> AgentState:
        """
        Process one customer request and return the final AgentState.

        session must contain:
          customer_id : str  — authenticated customer identity (never from user message)
          auth_level  : int  — caller's authorization level (1 or 2)
          request_id  : str  — optional; generated if absent
        """
        state = AgentState(
            request_id=session.get("request_id") or str(uuid.uuid4()),
            customer_id=session["customer_id"],
            user_request=user_request,
        )

        _banner(f"START — request_id={state.request_id}  customer={state.customer_id}")
        print(f"  Request: {user_request}")

        # ── MEMORY READ: load case history before the loop ────────────────────
        # customer_id comes from the trusted session; the memory store only
        # returns records belonging to that customer.
        prior_cases = self._memory.read_cases(state.customer_id, state.request_id)
        state.memory_context = prior_cases

        if prior_cases:
            _step("MEMORY_LOADED",
                  f"{len(prior_cases)} prior case(s) found for this customer")
            for c in prior_cases:
                print(f"    ticket={c['ticket_id']} status={c['status']} "
                      f"category={c['category']}")
        else:
            _step("MEMORY_LOADED", "no prior cases — fresh customer session")

        # ── Main loop ─────────────────────────────────────────────────────────
        while state.attempt_count < MAX_ITERATIONS:
            iterations_left = MAX_ITERATIONS - state.attempt_count

            # ── PLAN ──────────────────────────────────────────────────────────
            plan = self._planner.decide(state, iterations_left)

            if plan is None:
                state.attempt_count += 1
                _step("CLASSIFY_REQUEST", "planner returned None — re-planning")
                continue

            action    = plan.get("action", "")
            tool_name = plan.get("tool") or None
            arguments = plan.get("arguments") or {}
            if plan.get("intent"):
                state.intent = plan["intent"]
            state.planned_action = action

            _step("CLASSIFY_REQUEST",
                  f"intent={state.intent!r}  action={action}  tool={tool_name}")

            # ── ACTION GATE ───────────────────────────────────────────────────
            state.attempt_count += 1

            # 1. Action must be in the allow-list
            if action not in ALLOWED_ACTIONS:
                _step("SELECT_ACTION",
                      f"REJECTED — unknown action '{action}'")
                continue

            # 2. Model must not inject identity fields
            if "customer_id" in arguments or "human_approval_token" in arguments:
                _step("SELECT_ACTION",
                      "REJECTED — model attempted to supply identity field")
                continue

            # 3. Tool (if any) must be in the allow-list
            if tool_name and tool_name not in ALLOWED_TOOLS:
                _step("SELECT_ACTION",
                      f"REJECTED — unknown tool '{tool_name}'")
                continue

            _step("SELECT_ACTION", f"APPROVED — action={action}")

            # ── No-tool terminal actions ───────────────────────────────────────
            if action == "answer_from_evidence":
                if state.retrieved_evidence:
                    state.final_response = _compose_answer(state)
                    _stop(state, "grounded_answer_produced", "ANSWERED_FROM_KNOWLEDGE")
                    break
                # No evidence yet — search first
                result = self._tool_call(
                    "search_knowledge_base", {"query": user_request}, session, state)
                _absorb_search(result, state)
                if result.get("status") == "error":
                    state.final_response = (
                        "The knowledge base is temporarily unavailable. "
                        "Please contact Centenary Bank support.")
                    _stop(state, "kb_unavailable", "TOOL_FAILURE_HANDOFF")
                    break
                continue

            elif action == "ask_for_clarification":
                state.final_response = (
                    plan.get("reason")
                    or "Could you please provide more details so I can help?")
                _stop(state, "clarification_needed", "CLARIFICATION_REQUIRED")
                break

            elif action == "refuse_or_handoff":
                state.final_response = (
                    "I'm sorry — this request is outside what I can help with. "
                    "Please contact Centenary Bank directly.")
                _stop(state, "out_of_scope", "OUT_OF_SCOPE_HANDOFF")
                break

            # ── Escalation approval gate ───────────────────────────────────────
            elif action == "request_escalation_approval":
                self._escalate(plan, session, state)
                break

            # ── Tool-calling actions ───────────────────────────────────────────
            else:
                state.retry_count = 0
                result = self._tool_call(tool_name, arguments, session, state)

                # Safe retry on service_unavailable (once only, per spec rule 7)
                if result.get("error_type") == "service_unavailable":
                    if state.retry_count < MAX_RETRY:
                        state.retry_count += 1
                        _step("RETRY_OR_STOP",
                              f"service unavailable — retrying {tool_name} "
                              f"(retry {state.retry_count}/{MAX_RETRY})")
                        result = self._tool_call(
                            tool_name, arguments, session, state)
                    if result.get("error_type") == "service_unavailable":
                        state.final_response = (
                            "A required service is temporarily unavailable. "
                            "Please try again later or contact support.")
                        _stop(state, "service_unavailable_after_retry",
                              "TOOL_FAILURE_HANDOFF")
                        break

                stop = self._observe(tool_name, result, state, session)
                if stop:
                    break

        # ── Iteration limit ────────────────────────────────────────────────────
        if not state.terminal_outcome:
            state.final_response = (
                "I was unable to fully resolve your request within the allowed "
                "steps.  Please contact Centenary Bank support.")
            _stop(state, "iteration_limit_reached", "ITERATION_LIMIT_REACHED")

        _banner(f"COMPLETE — outcome={state.terminal_outcome}")
        print(f"  Response: {state.final_response}")
        return state

    # ── Internal helpers ──────────────────────────────────────────────────────

    def _tool_call(self, tool_name: str, arguments: dict,
                   session: dict, state: AgentState) -> dict:
        """Build CallerContext from trusted session and call the orchestrator."""
        caller = CallerContext(
            auth_level=session.get("auth_level", 2),
            customer_id=session["customer_id"],
        )
        _step("EXECUTE_TOOL", f"calling {tool_name}  args={_safe_args(arguments)}")
        result = self._orchestrator.call(tool_name, arguments, caller)
        state.tool_calls.append({
            "tool":      tool_name,
            "arguments": _safe_args(arguments),
            "result":    result,
        })
        return result

    def _observe(self, tool_name: str, result: dict,
                 state: AgentState, session: dict) -> bool:
        """
        Inspect the tool result and update state.
        Returns True if the loop should stop, False to re-plan.
        """
        status     = result.get("status")
        error_type = result.get("error_type")
        res_data   = result.get("result") or {}
        status_code = res_data.get("status_code") if isinstance(res_data, dict) else None

        _step("OBSERVE_RESULT",
              f"tool={tool_name} status={status} code={status_code} "
              f"error_type={error_type}")

        if status == "error":
            if error_type == "unauthorized":
                state.final_response = (
                    "You are not authorized to perform this action.")
                _stop(state, "authorization_denied", "AUTHORIZATION_DENIED")
                return True
            if error_type == "unexpected_response":
                state.final_response = (
                    "An unexpected error occurred. "
                    "Please contact Centenary Bank support.")
                _stop(state, "unexpected_tool_response", "TOOL_FAILURE_HANDOFF")
                return True
            # invalid_arguments → re-plan
            return False

        if status == "success":
            if tool_name == "search_knowledge_base":
                _absorb_search(result, state)
                return False   # re-plan to answer

            if tool_name == "get_service_status":
                if status_code == "OK":
                    svcs  = res_data.get("services", [])
                    lines = "\n".join(
                        f"  {s['service_name']}: {s['status']}" for s in svcs)
                    state.final_response = f"Current service status:\n{lines}"
                    _stop(state, "service_status_returned", "SERVICE_STATUS_RETURNED")
                    return True

            if tool_name == "get_ticket_status":
                if status_code == "OK":
                    state.final_response = (
                        f"Ticket {res_data['ticket_id']} — "
                        f"Status: {res_data.get('status', 'unknown')}, "
                        f"Category: {res_data.get('category', 'unknown')}. "
                        f"Summary: {res_data.get('summary', '')}")
                    _stop(state, "ticket_status_returned", "TICKET_STATUS_RETURNED")
                    return True
                if status_code == "NOT_FOUND":
                    state.final_response = (
                        f"Ticket {res_data.get('ticket_id', '')} was not found.")
                    _stop(state, "ticket_not_found", "CLARIFICATION_REQUIRED")
                    return True
                if status_code == "UNAUTHORIZED":
                    state.final_response = (
                        "I can only access tickets that belong to your account.")
                    _stop(state, "ticket_unauthorized", "AUTHORIZATION_DENIED")
                    return True

            if tool_name == "create_support_ticket":
                if status_code == "OK":
                    tid = res_data.get("ticket_id", "")
                    state.final_response = (
                        f"Your support ticket has been created: {tid}. "
                        f"{res_data.get('confirmation_message', '')}")
                    _stop(state, "ticket_created", "TICKET_CREATED")

                    # ── MEMORY WRITE ─────────────────────────────────────────
                    # Triggered only after a confirmed successful ticket creation.
                    # The controller writes the record; the model never calls this.
                    self._write_memory_after_ticket(
                        session["customer_id"], state, res_data)
                    return True

            if tool_name == "escalate_support_case":
                if status_code == "OK":
                    state.final_response = (
                        f"Your case has been escalated "
                        f"(ID: {res_data.get('escalation_id', '')}). "
                        f"Assigned to: {res_data.get('assigned_to', 'Human Support Team')}.")
                    _stop(state, "escalated_after_approval", "ESCALATED_AFTER_APPROVAL")
                    return True
                if status_code == "UNAUTHORIZED":
                    state.final_response = (
                        "The escalation could not be completed — approval mismatch.")
                    _stop(state, "escalation_token_mismatch", "AUTHORIZATION_DENIED")
                    return True

        return False

    def _escalate(self, plan: dict, session: dict, state: AgentState) -> None:
        """
        Human-approval gate for escalation.

        KEY TEACHING POINT: memory_context may show an existing case, but it
        cannot automatically grant approval.  The approval gate always runs.
        """
        args           = plan.get("arguments") or {}
        case_reference = args.get("case_reference", "UNKNOWN")
        reason         = args.get("reason", "Customer escalation request.")
        urgency        = args.get("urgency", "medium")

        state.approval_status = "pending"
        _step("REQUEST_APPROVAL",
              f"case={case_reference} urgency={urgency}")
        print("  NOTE: memory_context may show this case — "
              "it does NOT automatically approve escalation.")

        approved = self._approval_handler(case_reference, reason, urgency)

        if approved:
            state.approval_status = "approved"
            token = f"APPR-{state.request_id[:8]}-{state.attempt_count:02d}"
            self._approvals[token] = {
                "case_reference": case_reference,
                "reason":         reason,
                "urgency":        urgency,
            }
            approved_ctx = CallerContext(
                auth_level=session.get("auth_level", 2),
                customer_id=session["customer_id"],
                human_approved=True,
                human_approval_token=token,
            )
            _step("EXECUTE_TOOL",
                  f"escalate_support_case (token={token[:12]}...)")
            result = self._orchestrator.call(
                "escalate_support_case",
                {"case_reference": case_reference,
                 "reason": reason, "urgency": urgency},
                approved_ctx,
            )
            state.tool_calls.append({
                "tool":      "escalate_support_case",
                "arguments": {"case_reference": case_reference,
                              "reason": reason, "urgency": urgency},
                "result":    result,
            })
            res_data = result.get("result") or {}
            if result.get("status") == "success" and res_data.get("status_code") == "OK":
                state.final_response = (
                    f"Your case has been escalated "
                    f"(ID: {res_data.get('escalation_id', '')}). "
                    f"Assigned to: {res_data.get('assigned_to', 'Human Support Team')}.")
                _stop(state, "escalated_after_approval", "ESCALATED_AFTER_APPROVAL")
            else:
                state.final_response = (
                    "Escalation failed after approval. "
                    "Please contact support directly.")
                _stop(state, "escalation_failed", "TOOL_FAILURE_HANDOFF")
        else:
            state.approval_status = "denied"
            state.final_response = (
                "The escalation was not approved at this time. "
                "For urgent matters, please contact Centenary Bank directly.")
            _stop(state, "escalation_denied", "OUT_OF_SCOPE_HANDOFF")

    def _write_memory_after_ticket(self, customer_id: str,
                                   state: AgentState, ticket_data: dict) -> None:
        """
        Write a case record to the memory store after confirmed ticket creation.

        This is called by the controller (trusted code), not by the model.
        The model cannot call this — the controller decides WHEN to write memory.
        """
        ok = self._memory.write_case(
            customer_id=customer_id,
            case_data={
                "ticket_id":   ticket_data.get("ticket_id", ""),
                "category":    state.intent or "other",
                "summary":     state.user_request[:200],
                "status":      "open",
                "last_action": "ticket_created",
            },
            request_id=state.request_id,
        )
        if ok:
            _step("MEMORY_WRITE",
                  f"case record stored for ticket {ticket_data.get('ticket_id', '')}")
        else:
            _step("MEMORY_WRITE", "FAILED — validation rejected the record")


# ── Module helpers ────────────────────────────────────────────────────────────

def _banner(text: str) -> None:
    print(f"\n{'='*60}")
    print(f"  {text}")
    print(f"{'='*60}")


def _step(stage: str, detail: str) -> None:
    print(f"  [{stage}] {detail}")


def _stop(state: AgentState, reason: str, outcome: str) -> None:
    state.stop_reason      = reason
    state.terminal_outcome = outcome
    _step("RESPOND", f"stop_reason={reason}  outcome={outcome}")


def _safe_args(arguments: dict) -> dict:
    """Remove identity fields before logging."""
    return {k: v for k, v in arguments.items()
            if k not in ("customer_id", "human_approval_token")}


def _absorb_search(result: dict, state: AgentState) -> None:
    if result.get("status") == "success":
        for item in (result.get("result") or {}).get("results", []):
            state.retrieved_evidence.append({
                "marker":    item.get("marker", ""),
                "doc_id":    item.get("doc_id", ""),
                "doc_title": item.get("doc_title", ""),
                "text":      item.get("text", ""),
                "score":     item.get("score", 0),
            })


def _compose_answer(state: AgentState) -> str:
    lines = [f"[{e['marker']}] {e['text']}" for e in state.retrieved_evidence]
    return (
        "Based on Centenary Bank's knowledge base:\n\n"
        + "\n\n".join(lines)
        + "\n\nIf you need further assistance, please contact support."
    )


def _console_approval_gate(case_reference: str, reason: str, urgency: str) -> bool:
    print("\n--- HUMAN APPROVAL REQUIRED ---")
    print(f"  Case : {case_reference}")
    print(f"  Reason: {reason}")
    print(f"  Urgency: {urgency}")
    print("--------------------------------")
    answer = input("Approve escalation? (yes/no): ").strip().lower()
    return answer == "yes"
